resources:
  - repo: self

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true

trigger:
  batch: true
  branches:
    include:
      - master

stages:
- stage: Build
  displayName: Build images
  jobs:  
  - job: Build
    displayName: Build 0.12.x image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'build'
        arguments: '--build-arg TERRAFORM_VERSION=$(tf_0.12_version)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 0.12
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'push'
        tags: 0.12

  - job: Build2
    displayName: Build 0.13.x image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'build'
        arguments: '--build-arg TERRAFORM_VERSION=$(tf_0.13_version)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 0.13
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'push'
        tags: 0.13

  - job: Build3
    displayName: Build 0.14.x image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'build'
        arguments: '--build-arg TERRAFORM_VERSION=$(tf_0.14_version)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 0.14
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: $(registry)
        repository: $(repository)
        command: 'push'
        tags: 0.14